# Generated by Django 3.1 on 2020-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('has_central', models.BooleanField(default=False)),
                ('blend_mode', models.CharField(max_length=50)),
                ('fly_mode', models.CharField(max_length=50)),
                ('final_shot', models.CharField(max_length=50)),
                ('final_datetime', models.DateTimeField()),
                ('project_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('background_image', models.ImageField(upload_to='')),
                ('background_color', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='is_central',
            field=models.BooleanField(default=False),
        ),
    ]
