# Generated by Django 3.1 on 2020-08-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200821_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.IntegerField(default=0),
        ),
    ]
