# Generated by Django 3.1 on 2020-08-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200821_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'проект', 'verbose_name_plural': 'проекты'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='final_datetime',
        ),
    ]
