# Generated by Django 3.1.1 on 2020-09-05 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('num_of_participants', models.IntegerField(verbose_name='Количество участников')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, verbose_name='Адрес страницы')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('header_color', models.CharField(max_length=20, verbose_name='Цвет заголовка')),
                ('background_color', models.CharField(max_length=20, verbose_name='Цвет страницы')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend_mode', models.CharField(choices=[('1', 'Вариант 1'), ('2', 'Вариант 2'), ('3', 'Вариант 3'), ('4', 'Вариант 4'), ('5', 'Вариант 5')], default='1', max_length=2, verbose_name='Способ наложения')),
                ('fly_mode', models.CharField(choices=[('1', 'Вариант 1'), ('2', 'Вариант 2'), ('3', 'Вариант 3'), ('4', 'Вариант 4'), ('5', 'Вариант 5')], default='1', max_length=2, verbose_name='Способ слета фото')),
                ('final_shot', models.CharField(max_length=50, verbose_name='Финальный кадр')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'verbose_name': 'видео',
                'verbose_name_plural': 'видео',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Файл')),
                ('is_central', models.BooleanField(default=False, verbose_name='Центр')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
    ]
