# Generated by Django 3.1 on 2020-08-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Файл')),
                ('project_id', models.IntegerField(default=0, verbose_name='ID проекта')),
                ('is_central', models.BooleanField(default=False, verbose_name='Центр')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('number_of_participants', models.IntegerField(verbose_name='Количество участников')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('blend_mode', models.CharField(choices=[('1', 'Вариант 1'), ('2', 'Вариант 2'), ('3', 'Вариант 3'), ('4', 'Вариант 4'), ('5', 'Вариант 5')], default='1', max_length=2, verbose_name='Способ наложения')),
                ('fly_mode', models.CharField(choices=[('1', 'Вариант 1'), ('2', 'Вариант 2'), ('3', 'Вариант 3'), ('4', 'Вариант 4'), ('5', 'Вариант 5')], max_length=2, verbose_name='Способ слета фото')),
                ('final_shot', models.CharField(max_length=50, verbose_name='Финальный кадр')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('background_color', models.CharField(max_length=20, verbose_name='Цвет фона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
