# Generated by Django 3.1.1 on 2020-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesettings',
            name='address',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(default=123, max_length=30, unique=True, verbose_name='Адрес страницы'),
            preserve_default=False,
        ),
    ]
