# Generated by Django 3.1.1 on 2020-09-07 10:23

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200907_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitesettings',
            options={'verbose_name': 'веб-страница', 'verbose_name_plural': 'веб-страницы'},
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='videosettings',
            name='final_shot',
            field=models.CharField(default='Финальный кадр', max_length=50, verbose_name='Финальный кадр'),
        ),
    ]
