# Generated by Django 3.1.1 on 2020-09-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200907_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='email',
            field=models.CharField(help_text='Мы вышлем финальное видео на данный email', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_of_participants',
            field=models.IntegerField(help_text='Приблизительное количество участников', verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='videosettings',
            name='final_shot',
            field=models.ImageField(help_text='Изображение, в которое слетаются фотографии', upload_to='', verbose_name='Финальный кадр'),
        ),
    ]
