# Generated by Django 3.1.1 on 2020-09-09 10:26

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200909_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(help_text='Адрес страницы, на которую будут заходить ваши посетители для загрузки своих фотографий', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='videosettings',
            name='final_shot',
            field=models.ImageField(default='FlyPhoto.png', help_text='Изображение, в которое слетаются фотографии', upload_to='', verbose_name='Финальный кадр'),
        ),
    ]
